// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YNhOmeQ9sGjIV3Ai60-ACH52enw4BS0',
    appId: '1:862898499355:web:27376c4b238b1e400cedbe',
    messagingSenderId: '862898499355',
    projectId: 'geomathapp-7b721',
    authDomain: 'geomathapp-7b721.firebaseapp.com',
    storageBucket: 'geomathapp-7b721.appspot.com',
    measurementId: 'G-NQ89P0T06S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYT4h9eaDMItdl2ailREmvDDMZBrmYXpY',
    appId: '1:862898499355:android:38b9120c99383ade0cedbe',
    messagingSenderId: '862898499355',
    projectId: 'geomathapp-7b721',
    storageBucket: 'geomathapp-7b721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDkiTgevAaEX64GtuOocWc9XEuKAD45c',
    appId: '1:862898499355:ios:cce12beca1ec9c8a0cedbe',
    messagingSenderId: '862898499355',
    projectId: 'geomathapp-7b721',
    storageBucket: 'geomathapp-7b721.appspot.com',
    iosClientId: '862898499355-f4fkrlrcj0g48im2suh9cio3nsspas7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.geomathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDkiTgevAaEX64GtuOocWc9XEuKAD45c',
    appId: '1:862898499355:ios:cce12beca1ec9c8a0cedbe',
    messagingSenderId: '862898499355',
    projectId: 'geomathapp-7b721',
    storageBucket: 'geomathapp-7b721.appspot.com',
    iosClientId: '862898499355-f4fkrlrcj0g48im2suh9cio3nsspas7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.geomathApp',
  );
}
